# Generated by Django 3.0.1 on 2021-01-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_auto_20210125_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='has_logo',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='has_side_banner',
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
