# Generated by Django 3.0.1 on 2021-01-25 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_auto_20210125_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_1',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_1_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_1_names', to='setup.Feature'),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_for',
            field=models.CharField(default='Motherboard, Graphic Card etc. ', max_length=254, null=True),
        ),
    ]
